name: Deploy to GitHub Pages

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.5.0
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Install
      run: pnpm ci
      shell: bash
    - name: Build
      run: pnpm build
      shell: bash
      env:
        NODE_ENV: production
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist
        name: github-actions
    - name: Deploy
      uses: actions/deploy-pages@v2
      with:
        artifact_name: github-actions
      id: deployment
